//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSClient.FlightReservationWS
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlightReservation", Namespace="http://schemas.datacontract.org/2004/07/WS.DataServices.Model")]
    public partial class FlightReservation : object
    {
        
        private string AirlineField;
        
        private WSClient.FlightReservationWS.DateOnly DepartureDateField;
        
        private string DestinationAirportField;
        
        private WSClient.FlightReservationWS.DateOnly DestinationDateField;
        
        private string DpartureAirportField;
        
        private string FlightIdField;
        
        private int IdField;
        
        private decimal PriceField;
        
        private int ReservationIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Airline
        {
            get
            {
                return this.AirlineField;
            }
            set
            {
                this.AirlineField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WSClient.FlightReservationWS.DateOnly DepartureDate
        {
            get
            {
                return this.DepartureDateField;
            }
            set
            {
                this.DepartureDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationAirport
        {
            get
            {
                return this.DestinationAirportField;
            }
            set
            {
                this.DestinationAirportField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WSClient.FlightReservationWS.DateOnly DestinationDate
        {
            get
            {
                return this.DestinationDateField;
            }
            set
            {
                this.DestinationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DpartureAirport
        {
            get
            {
                return this.DpartureAirportField;
            }
            set
            {
                this.DpartureAirportField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlightId
        {
            get
            {
                return this.FlightIdField;
            }
            set
            {
                this.FlightIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReservationID
        {
            get
            {
                return this.ReservationIDField;
            }
            set
            {
                this.ReservationIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DateOnly", Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial struct DateOnly
    {
        
        private int DayField;
        
        private int DayNumberField;
        
        private System.DayOfWeek DayOfWeekField;
        
        private int DayOfYearField;
        
        private WSClient.FlightReservationWS.DateOnly MaxValueField;
        
        private WSClient.FlightReservationWS.DateOnly MinValueField;
        
        private int MonthField;
        
        private int YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Day
        {
            get
            {
                return this.DayField;
            }
            set
            {
                this.DayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DayNumber
        {
            get
            {
                return this.DayNumberField;
            }
            set
            {
                this.DayNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DayOfWeek DayOfWeek
        {
            get
            {
                return this.DayOfWeekField;
            }
            set
            {
                this.DayOfWeekField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DayOfYear
        {
            get
            {
                return this.DayOfYearField;
            }
            set
            {
                this.DayOfYearField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WSClient.FlightReservationWS.DateOnly MaxValue
        {
            get
            {
                return this.MaxValueField;
            }
            set
            {
                this.MaxValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WSClient.FlightReservationWS.DateOnly MinValue
        {
            get
            {
                return this.MinValueField;
            }
            set
            {
                this.MinValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Month
        {
            get
            {
                return this.MonthField;
            }
            set
            {
                this.MonthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                this.YearField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.agencytravel/flight/", ConfigurationName="WSClient.FlightReservationWS.IFlightReservationServices")]
    public interface IFlightReservationServices
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.agencytravel/flight/IFlightReservationServices/GetFlights", ReplyAction="http://ws.agencytravel/flight/IFlightReservationServices/GetFlightsResponse")]
        System.Threading.Tasks.Task<WSClient.FlightReservationWS.FlightReservation[]> GetFlightsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.agencytravel/flight/IFlightReservationServices/GetFlight", ReplyAction="http://ws.agencytravel/flight/IFlightReservationServices/GetFlightResponse")]
        System.Threading.Tasks.Task<WSClient.FlightReservationWS.FlightReservation> GetFlightAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.agencytravel/flight/IFlightReservationServices/CreateFlight", ReplyAction="http://ws.agencytravel/flight/IFlightReservationServices/CreateFlightResponse")]
        System.Threading.Tasks.Task CreateFlightAsync(WSClient.FlightReservationWS.FlightReservation flightReservation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.agencytravel/flight/IFlightReservationServices/UpdateFlight", ReplyAction="http://ws.agencytravel/flight/IFlightReservationServices/UpdateFlightResponse")]
        System.Threading.Tasks.Task UpdateFlightAsync(WSClient.FlightReservationWS.FlightReservation flightReservation);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface IFlightReservationServicesChannel : WSClient.FlightReservationWS.IFlightReservationServices, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class FlightReservationServicesClient : System.ServiceModel.ClientBase<WSClient.FlightReservationWS.IFlightReservationServices>, WSClient.FlightReservationWS.IFlightReservationServices
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FlightReservationServicesClient() : 
                base(FlightReservationServicesClient.GetDefaultBinding(), FlightReservationServicesClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IFlightReservationServices.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FlightReservationServicesClient(EndpointConfiguration endpointConfiguration) : 
                base(FlightReservationServicesClient.GetBindingForEndpoint(endpointConfiguration), FlightReservationServicesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FlightReservationServicesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FlightReservationServicesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FlightReservationServicesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FlightReservationServicesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FlightReservationServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<WSClient.FlightReservationWS.FlightReservation[]> GetFlightsAsync()
        {
            return base.Channel.GetFlightsAsync();
        }
        
        public System.Threading.Tasks.Task<WSClient.FlightReservationWS.FlightReservation> GetFlightAsync(int id)
        {
            return base.Channel.GetFlightAsync(id);
        }
        
        public System.Threading.Tasks.Task CreateFlightAsync(WSClient.FlightReservationWS.FlightReservation flightReservation)
        {
            return base.Channel.CreateFlightAsync(flightReservation);
        }
        
        public System.Threading.Tasks.Task UpdateFlightAsync(WSClient.FlightReservationWS.FlightReservation flightReservation)
        {
            return base.Channel.UpdateFlightAsync(flightReservation);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IFlightReservationServices))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IFlightReservationServices))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:9090/FlightServices.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return FlightReservationServicesClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IFlightReservationServices);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return FlightReservationServicesClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IFlightReservationServices);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IFlightReservationServices,
        }
    }
}
