version: '3.9'
services:
  app:
    depends_on:
    - data
    - travelapi
    - security
    deploy:
      replicas: 1
    image: dorviz/agency_app
    environment: 
      - ApplicationSettings__SecurityEndPoint=https://security:443/api/tokens
      - ApplicationSettings__CountriesEndPoint=http://travelapi:8080/travelApi/api/v1/countries
      - ApplicationSettings__AirportsEndPoint=http://travelapi:8080/travelApi/api/v1/airports
      - ApplicationSettings__FlightEndPoint=http://travelapi:8080/travelApi/api/v1/flights
      - ApplicationSettings__AppDataFlightServiceEndPoint=http://data:80/FlightServices.svc
      - ApplicationSettings__AppDataReservationServiceEndPoint=http://data:80/ReservationServices.svc
      - ApplicationSettings__AppDataUserServiceEndPoint=http://data:80/UserServices.svc
    ports:
    - published: 8082
      target: 80
  data:
    deploy:
      replicas: 1
    image: dorviz/agency_data
      
  travelapi:
    deploy:
      replicas: 1
    image: dorviz/travel_api
  security:
    deploy:
      replicas: 1
    image: dorviz/security
    ports:
    - published: 9060
      target: 80
  web:
    deploy:
      replicas: 1
    image: dorviz/agency_web
    ports:
    - published: 6060
      target: 2000